{"name":"Emails from WH to LH","ppdf:dataflowId":"45b2be39-1f1d-4a5d-80a6-a2c5f8259e97","ppdf:owner":{"tenantId":"0b3fc178-b730-4e8b-9843-e81259237b77","userId":"fc487b5c-5b0a-4c85-a873-53170d27b296"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2024-02-23T13:07:13.752525+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Enron_emails_full_list_v1":{"queryId":"973e402a-f7f8-4381-bb0b-78c63e0ebfac","queryName":"Enron_emails_full_list_v1","loadEnabled":true},"Enron_emails_full_list_v1_DataDestination":{"queryId":"09e4f887-8fee-4665-8643-60ee0c26a924","queryName":"Enron_emails_full_list_v1_DataDestination"},"Enron_emails_full_list_v1_WriteToDataDestination":{"queryId":"b64e5072-432b-4a01-99ab-4b29da87b427","queryName":"Enron_emails_full_list_v1_WriteToDataDestination"},"Enron_emails_full_list_v1_TransformForWriteToDataDestination":{"queryId":"bb321b82-a40d-4a4d-b080-a3dcce3ae4e9","queryName":"Enron_emails_full_list_v1_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared Enron_emails_full_list_v1 = let\r\n  Source = Fabric.Warehouse(null){[workspaceId = \"8034d15b-bf56-4837-b4d0-97c890988106\"]}[Data]{[warehouseId = \"b02b0681-4b51-445f-bd8c-9993fc7230fc\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"Enron_emails_full_list_v1\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared Enron_emails_full_list_v1_DataDestination = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"8034d15b-bf56-4837-b4d0-97c890988106\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"d9def709-2031-4142-83c2-8694c4923a5a\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"Enron_emails_full_list_v1\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[#\"Message-ID\" = nullable Text.Type, Date = nullable Text.Type, From = nullable Text.Type, To = nullable Text.Type, Subject = nullable Text.Type, #\"X-From\" = nullable Text.Type, #\"X-To\" = nullable Text.Type, #\"X-cc\" = nullable Text.Type, #\"X-bcc\" = nullable Text.Type, #\"X-Folder\" = nullable Text.Type, #\"X-Origin\" = nullable Text.Type, #\"X-FileName\" = nullable Text.Type, content = nullable Text.Type, user = nullable Text.Type, Cat_1_level_1 = nullable Text.Type, Cat_1_level_2 = nullable Text.Type, Cat_1_weight = nullable Text.Type, Cat_2_level_1 = nullable Text.Type, Cat_2_level_2 = nullable Text.Type, Cat_2_weight = nullable Text.Type, Cat_3_level_1 = nullable Text.Type, Cat_3_level_2 = nullable Text.Type, Cat_3_weight = nullable Text.Type, Cat_4_level_1 = nullable Text.Type, Cat_4_level_2 = nullable Text.Type, Cat_4_weight = nullable Text.Type, Cat_5_level_1 = nullable Text.Type, Cat_5_level_2 = nullable Text.Type, Cat_5_weight = nullable Text.Type, Cat_6_level_1 = nullable Text.Type, Cat_6_level_2 = nullable Text.Type, Cat_6_weight = nullable Text.Type, Cat_7_level_1 = nullable Text.Type, Cat_7_level_2 = nullable Text.Type, Cat_7_weight = nullable Text.Type, Cat_8_level_1 = nullable Text.Type, Cat_8_level_2 = nullable Text.Type, Cat_8_weight = nullable Text.Type, Cat_9_level_1 = nullable Text.Type, Cat_9_level_2 = nullable Text.Type, Cat_9_weight = nullable Text.Type, Cat_10_level_1 = nullable Text.Type, Cat_10_level_2 = nullable Text.Type, Cat_10_weight = nullable Text.Type, Cat_11_level_1 = nullable Text.Type, Cat_11_level_2 = nullable Text.Type, Cat_11_weight = nullable Text.Type, Cat_12_level_1 = nullable Text.Type, Cat_12_level_2 = nullable Text.Type, Cat_12_weight = nullable Text.Type, labeled = nullable Text.Type], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared Enron_emails_full_list_v1_WriteToDataDestination = let\r\n  Enron_emails_full_list_v1_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = Enron_emails_full_list_v1_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], Enron_emails_full_list_v1_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  Enron_emails_full_list_v1_WriteToDataDestination;\r\nshared Enron_emails_full_list_v1_TransformForWriteToDataDestination = let\r\n    ColumnMappings = {[SourceColumnName = \"Message-ID\", DestinationColumnName = \"Message-ID\"], [SourceColumnName = \"Date\", DestinationColumnName = \"Date\"], [SourceColumnName = \"From\", DestinationColumnName = \"From\"], [SourceColumnName = \"To\", DestinationColumnName = \"To\"], [SourceColumnName = \"Subject\", DestinationColumnName = \"Subject\"], [SourceColumnName = \"X-From\", DestinationColumnName = \"X-From\"], [SourceColumnName = \"X-To\", DestinationColumnName = \"X-To\"], [SourceColumnName = \"X-cc\", DestinationColumnName = \"X-cc\"], [SourceColumnName = \"X-bcc\", DestinationColumnName = \"X-bcc\"], [SourceColumnName = \"X-Folder\", DestinationColumnName = \"X-Folder\"], [SourceColumnName = \"X-Origin\", DestinationColumnName = \"X-Origin\"], [SourceColumnName = \"X-FileName\", DestinationColumnName = \"X-FileName\"], [SourceColumnName = \"content\", DestinationColumnName = \"content\"], [SourceColumnName = \"user\", DestinationColumnName = \"user\"], [SourceColumnName = \"Cat_1_level_1\", DestinationColumnName = \"Cat_1_level_1\"], [SourceColumnName = \"Cat_1_level_2\", DestinationColumnName = \"Cat_1_level_2\"], [SourceColumnName = \"Cat_1_weight\", DestinationColumnName = \"Cat_1_weight\"], [SourceColumnName = \"Cat_2_level_1\", DestinationColumnName = \"Cat_2_level_1\"], [SourceColumnName = \"Cat_2_level_2\", DestinationColumnName = \"Cat_2_level_2\"], [SourceColumnName = \"Cat_2_weight\", DestinationColumnName = \"Cat_2_weight\"], [SourceColumnName = \"Cat_3_level_1\", DestinationColumnName = \"Cat_3_level_1\"], [SourceColumnName = \"Cat_3_level_2\", DestinationColumnName = \"Cat_3_level_2\"], [SourceColumnName = \"Cat_3_weight\", DestinationColumnName = \"Cat_3_weight\"], [SourceColumnName = \"Cat_4_level_1\", DestinationColumnName = \"Cat_4_level_1\"], [SourceColumnName = \"Cat_4_level_2\", DestinationColumnName = \"Cat_4_level_2\"], [SourceColumnName = \"Cat_4_weight\", DestinationColumnName = \"Cat_4_weight\"], [SourceColumnName = \"Cat_5_level_1\", DestinationColumnName = \"Cat_5_level_1\"], [SourceColumnName = \"Cat_5_level_2\", DestinationColumnName = \"Cat_5_level_2\"], [SourceColumnName = \"Cat_5_weight\", DestinationColumnName = \"Cat_5_weight\"], [SourceColumnName = \"Cat_6_level_1\", DestinationColumnName = \"Cat_6_level_1\"], [SourceColumnName = \"Cat_6_level_2\", DestinationColumnName = \"Cat_6_level_2\"], [SourceColumnName = \"Cat_6_weight\", DestinationColumnName = \"Cat_6_weight\"], [SourceColumnName = \"Cat_7_level_1\", DestinationColumnName = \"Cat_7_level_1\"], [SourceColumnName = \"Cat_7_level_2\", DestinationColumnName = \"Cat_7_level_2\"], [SourceColumnName = \"Cat_7_weight\", DestinationColumnName = \"Cat_7_weight\"], [SourceColumnName = \"Cat_8_level_1\", DestinationColumnName = \"Cat_8_level_1\"], [SourceColumnName = \"Cat_8_level_2\", DestinationColumnName = \"Cat_8_level_2\"], [SourceColumnName = \"Cat_8_weight\", DestinationColumnName = \"Cat_8_weight\"], [SourceColumnName = \"Cat_9_level_1\", DestinationColumnName = \"Cat_9_level_1\"], [SourceColumnName = \"Cat_9_level_2\", DestinationColumnName = \"Cat_9_level_2\"], [SourceColumnName = \"Cat_9_weight\", DestinationColumnName = \"Cat_9_weight\"], [SourceColumnName = \"Cat_10_level_1\", DestinationColumnName = \"Cat_10_level_1\"], [SourceColumnName = \"Cat_10_level_2\", DestinationColumnName = \"Cat_10_level_2\"], [SourceColumnName = \"Cat_10_weight\", DestinationColumnName = \"Cat_10_weight\"], [SourceColumnName = \"Cat_11_level_1\", DestinationColumnName = \"Cat_11_level_1\"], [SourceColumnName = \"Cat_11_level_2\", DestinationColumnName = \"Cat_11_level_2\"], [SourceColumnName = \"Cat_11_weight\", DestinationColumnName = \"Cat_11_weight\"], [SourceColumnName = \"Cat_12_level_1\", DestinationColumnName = \"Cat_12_level_1\"], [SourceColumnName = \"Cat_12_level_2\", DestinationColumnName = \"Cat_12_level_2\"], [SourceColumnName = \"Cat_12_weight\", DestinationColumnName = \"Cat_12_weight\"], [SourceColumnName = \"labeled\", DestinationColumnName = \"labeled\"]},\r\n    SourceColumns = Table.SelectColumns(Enron_emails_full_list_v1, List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\n","connectionOverrides":[{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"Enron_emails_full_list_v1","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Enron_emails_full_list_v1.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"Message-ID","dataType":"string"},{"name":"Date","dataType":"string"},{"name":"From","dataType":"string"},{"name":"To","dataType":"string"},{"name":"Subject","dataType":"string"},{"name":"X-From","dataType":"string"},{"name":"X-To","dataType":"string"},{"name":"X-cc","dataType":"string"},{"name":"X-bcc","dataType":"string"},{"name":"X-Folder","dataType":"string"},{"name":"X-Origin","dataType":"string"},{"name":"X-FileName","dataType":"string"},{"name":"content","dataType":"string"},{"name":"user","dataType":"string"},{"name":"Cat_1_level_1","dataType":"string"},{"name":"Cat_1_level_2","dataType":"string"},{"name":"Cat_1_weight","dataType":"string"},{"name":"Cat_2_level_1","dataType":"string"},{"name":"Cat_2_level_2","dataType":"string"},{"name":"Cat_2_weight","dataType":"string"},{"name":"Cat_3_level_1","dataType":"string"},{"name":"Cat_3_level_2","dataType":"string"},{"name":"Cat_3_weight","dataType":"string"},{"name":"Cat_4_level_1","dataType":"string"},{"name":"Cat_4_level_2","dataType":"string"},{"name":"Cat_4_weight","dataType":"string"},{"name":"Cat_5_level_1","dataType":"string"},{"name":"Cat_5_level_2","dataType":"string"},{"name":"Cat_5_weight","dataType":"string"},{"name":"Cat_6_level_1","dataType":"string"},{"name":"Cat_6_level_2","dataType":"string"},{"name":"Cat_6_weight","dataType":"string"},{"name":"Cat_7_level_1","dataType":"string"},{"name":"Cat_7_level_2","dataType":"string"},{"name":"Cat_7_weight","dataType":"string"},{"name":"Cat_8_level_1","dataType":"string"},{"name":"Cat_8_level_2","dataType":"string"},{"name":"Cat_8_weight","dataType":"string"},{"name":"Cat_9_level_1","dataType":"string"},{"name":"Cat_9_level_2","dataType":"string"},{"name":"Cat_9_weight","dataType":"string"},{"name":"Cat_10_level_1","dataType":"string"},{"name":"Cat_10_level_2","dataType":"string"},{"name":"Cat_10_weight","dataType":"string"},{"name":"Cat_11_level_1","dataType":"string"},{"name":"Cat_11_level_2","dataType":"string"},{"name":"Cat_11_weight","dataType":"string"},{"name":"Cat_12_level_1","dataType":"string"},{"name":"Cat_12_level_2","dataType":"string"},{"name":"Cat_12_weight","dataType":"string"},{"name":"labeled","dataType":"string"}]}]}