{"name":"Initial input of e-mail data to WH","ppdf:dataflowId":"159ff0ac-c448-4298-9ddc-82ef566513f2","ppdf:owner":{"tenantId":"0b3fc178-b730-4e8b-9843-e81259237b77","userId":"fc487b5c-5b0a-4c85-a873-53170d27b296"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2024-02-23T12:07:43.2980902+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":true,"allowNativeQueries":false,"queriesMetadata":{"enron_05_17_2015_with_labels_v2_100K_chunk_1_of_6":{"queryId":"0478626c-bd39-4199-bd04-a341203f70a6","queryName":"enron_05_17_2015_with_labels_v2_100K_chunk_1_of_6"},"enron_05_17_2015_with_labels_v2_100K_chunk_2_of_6":{"queryId":"e8f18485-035f-40df-92d5-a3da85c1ac02","queryName":"enron_05_17_2015_with_labels_v2_100K_chunk_2_of_6"},"enron_05_17_2015_with_labels_v2_100K_chunk_3_of_6":{"queryId":"689bf0d9-61f1-4bd3-aa21-51c38b422684","queryName":"enron_05_17_2015_with_labels_v2_100K_chunk_3_of_6"},"enron_05_17_2015_with_labels_v2_100K_chunk_5_of_6":{"queryId":"9daf58ef-746f-41b3-a81d-f1e02087bd61","queryName":"enron_05_17_2015_with_labels_v2_100K_chunk_5_of_6"},"enron_05_17_2015_with_labels_v2_100K_chunk_4_of_6":{"queryId":"b0d72c05-bff1-485c-8d91-64e16e629ef8","queryName":"enron_05_17_2015_with_labels_v2_100K_chunk_4_of_6"},"enron_05_17_2015_with_labels_v2_100K_chunk_6_of_6":{"queryId":"113feda1-4775-4451-be03-3f70489e9977","queryName":"enron_05_17_2015_with_labels_v2_100K_chunk_6_of_6"},"Append":{"queryId":"0516fe28-d514-4db7-a788-1a9fdc68a040","queryName":"Append","loadEnabled":true},"Append_DataDestination":{"queryId":"79d8ec8e-b3a7-4130-b3c6-8375827917fc","queryName":"Append_DataDestination"},"Append_WriteToDataDestination":{"queryId":"d38ee1b5-6620-4edb-9d6b-98c6246213fc","queryName":"Append_WriteToDataDestination"},"Append_TransformForWriteToDataDestination":{"queryId":"70604557-eecc-41c0-8703-840e17439fd1","queryName":"Append_TransformForWriteToDataDestination"}},"document":"section Section1;\r\nshared enron_05_17_2015_with_labels_v2_100K_chunk_1_of_6 = let\r\n  Source = Csv.Document(Web.Contents(\"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/Documents/Apps/Microsoft Power Query/Uploaded Files/enron_05_17_2015_with_labels_v2_100K_chunk_1_of_6.csv\"), [Delimiter = \",\", Columns = 52, Encoding = 65001]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"\", Int64.Type}, {\"Message-ID\", type text}, {\"Date\", type datetime}, {\"From\", type text}, {\"To\", type text}, {\"Subject\", type text}, {\"X-From\", type text}, {\"X-To\", type text}, {\"X-cc\", type text}, {\"X-bcc\", type text}, {\"X-Folder\", type text}, {\"X-Origin\", type text}, {\"X-FileName\", type text}, {\"content\", type text}, {\"user\", type text}, {\"Cat_1_level_1\", type text}, {\"Cat_1_level_2\", type text}, {\"Cat_1_weight\", type text}, {\"Cat_2_level_1\", type text}, {\"Cat_2_level_2\", type text}, {\"Cat_2_weight\", type text}, {\"Cat_3_level_1\", type text}, {\"Cat_3_level_2\", type text}, {\"Cat_3_weight\", type text}, {\"Cat_4_level_1\", type text}, {\"Cat_4_level_2\", type text}, {\"Cat_4_weight\", type text}, {\"Cat_5_level_1\", type text}, {\"Cat_5_level_2\", type text}, {\"Cat_5_weight\", type text}, {\"Cat_6_level_1\", type text}, {\"Cat_6_level_2\", type text}, {\"Cat_6_weight\", type text}, {\"Cat_7_level_1\", type text}, {\"Cat_7_level_2\", type text}, {\"Cat_7_weight\", type text}, {\"Cat_8_level_1\", type text}, {\"Cat_8_level_2\", type text}, {\"Cat_8_weight\", type text}, {\"Cat_9_level_1\", type text}, {\"Cat_9_level_2\", type text}, {\"Cat_9_weight\", type text}, {\"Cat_10_level_1\", type text}, {\"Cat_10_level_2\", type text}, {\"Cat_10_weight\", type text}, {\"Cat_11_level_1\", type text}, {\"Cat_11_level_2\", type text}, {\"Cat_11_weight\", type text}, {\"Cat_12_level_1\", type text}, {\"Cat_12_level_2\", type text}, {\"Cat_12_weight\", type text}, {\"labeled\", type logical}})\r\nin\r\n  #\"Changed column type\";\r\nshared enron_05_17_2015_with_labels_v2_100K_chunk_2_of_6 = let\r\n  Source = Csv.Document(Web.Contents(\"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/Documents/Apps/Microsoft Power Query/Uploaded Files/enron_05_17_2015_with_labels_v2_100K_chunk_2_of_6.csv\"), [Delimiter = \",\", Columns = 52, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"\", type text}, {\"Message-ID\", type text}, {\"Date\", type text}, {\"From\", type text}, {\"To\", type text}, {\"Subject\", type text}, {\"X-From\", type text}, {\"X-To\", type text}, {\"X-cc\", type text}, {\"X-bcc\", type text}, {\"X-Folder\", type text}, {\"X-Origin\", type text}, {\"X-FileName\", type text}, {\"content\", type text}, {\"user\", type text}, {\"Cat_1_level_1\", type text}, {\"Cat_1_level_2\", type text}, {\"Cat_1_weight\", type text}, {\"Cat_2_level_1\", type text}, {\"Cat_2_level_2\", type text}, {\"Cat_2_weight\", type text}, {\"Cat_3_level_1\", type text}, {\"Cat_3_level_2\", type text}, {\"Cat_3_weight\", type text}, {\"Cat_4_level_1\", type text}, {\"Cat_4_level_2\", type text}, {\"Cat_4_weight\", type text}, {\"Cat_5_level_1\", type text}, {\"Cat_5_level_2\", type text}, {\"Cat_5_weight\", type text}, {\"Cat_6_level_1\", type text}, {\"Cat_6_level_2\", type text}, {\"Cat_6_weight\", type text}, {\"Cat_7_level_1\", type text}, {\"Cat_7_level_2\", type text}, {\"Cat_7_weight\", type text}, {\"Cat_8_level_1\", type text}, {\"Cat_8_level_2\", type text}, {\"Cat_8_weight\", type text}, {\"Cat_9_level_1\", type text}, {\"Cat_9_level_2\", type text}, {\"Cat_9_weight\", type text}, {\"Cat_10_level_1\", type text}, {\"Cat_10_level_2\", type text}, {\"Cat_10_weight\", type text}, {\"Cat_11_level_1\", type text}, {\"Cat_11_level_2\", type logical}, {\"Cat_11_weight\", type text}, {\"Cat_12_level_1\", type text}, {\"Cat_12_level_2\", type text}, {\"Cat_12_weight\", type text}, {\"labeled\", type logical}})\r\nin\r\n  #\"Changed column type\";\r\nshared enron_05_17_2015_with_labels_v2_100K_chunk_3_of_6 = let\r\n  Source = Csv.Document(Web.Contents(\"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/Documents/Apps/Microsoft Power Query/Uploaded Files/enron_05_17_2015_with_labels_v2_100K_chunk_3_of_6.csv\"), [Delimiter = \",\", Columns = 52, QuoteStyle = QuoteStyle.Csv]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"\", Int64.Type}, {\"Message-ID\", type text}, {\"Date\", type datetime}, {\"From\", type text}, {\"To\", type text}, {\"Subject\", type text}, {\"X-From\", type text}, {\"X-To\", type text}, {\"X-cc\", type text}, {\"X-bcc\", type text}, {\"X-Folder\", type text}, {\"X-Origin\", type text}, {\"X-FileName\", type text}, {\"content\", type text}, {\"user\", type text}, {\"Cat_1_level_1\", type text}, {\"Cat_1_level_2\", type text}, {\"Cat_1_weight\", type text}, {\"Cat_2_level_1\", type text}, {\"Cat_2_level_2\", type text}, {\"Cat_2_weight\", type text}, {\"Cat_3_level_1\", type text}, {\"Cat_3_level_2\", type text}, {\"Cat_3_weight\", type text}, {\"Cat_4_level_1\", type text}, {\"Cat_4_level_2\", type text}, {\"Cat_4_weight\", type text}, {\"Cat_5_level_1\", type text}, {\"Cat_5_level_2\", type text}, {\"Cat_5_weight\", type text}, {\"Cat_6_level_1\", type text}, {\"Cat_6_level_2\", type text}, {\"Cat_6_weight\", type text}, {\"Cat_7_level_1\", type text}, {\"Cat_7_level_2\", type text}, {\"Cat_7_weight\", type text}, {\"Cat_8_level_1\", type text}, {\"Cat_8_level_2\", type text}, {\"Cat_8_weight\", type text}, {\"Cat_9_level_1\", type text}, {\"Cat_9_level_2\", type text}, {\"Cat_9_weight\", type text}, {\"Cat_10_level_1\", type text}, {\"Cat_10_level_2\", type text}, {\"Cat_10_weight\", type text}, {\"Cat_11_level_1\", type text}, {\"Cat_11_level_2\", type text}, {\"Cat_11_weight\", type text}, {\"Cat_12_level_1\", type text}, {\"Cat_12_level_2\", type text}, {\"Cat_12_weight\", type text}, {\"labeled\", type logical}})\r\nin\r\n  #\"Changed column type\";\r\nshared enron_05_17_2015_with_labels_v2_100K_chunk_5_of_6 = let\r\n  Source = Csv.Document(Web.Contents(\"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/Documents/Apps/Microsoft Power Query/Uploaded Files/enron_05_17_2015_with_labels_v2_100K_chunk_5_of_6.csv\"), [Delimiter = \",\", Columns = 52, QuoteStyle = QuoteStyle.Csv]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"\", Int64.Type}, {\"Message-ID\", type text}, {\"Date\", type datetime}, {\"From\", type text}, {\"To\", type text}, {\"Subject\", type text}, {\"X-From\", type text}, {\"X-To\", type text}, {\"X-cc\", type text}, {\"X-bcc\", type text}, {\"X-Folder\", type text}, {\"X-Origin\", type text}, {\"X-FileName\", type text}, {\"content\", type text}, {\"user\", type text}, {\"Cat_1_level_1\", type text}, {\"Cat_1_level_2\", type text}, {\"Cat_1_weight\", type text}, {\"Cat_2_level_1\", type text}, {\"Cat_2_level_2\", type text}, {\"Cat_2_weight\", type text}, {\"Cat_3_level_1\", type text}, {\"Cat_3_level_2\", type text}, {\"Cat_3_weight\", type text}, {\"Cat_4_level_1\", type text}, {\"Cat_4_level_2\", type text}, {\"Cat_4_weight\", type text}, {\"Cat_5_level_1\", type text}, {\"Cat_5_level_2\", type text}, {\"Cat_5_weight\", type text}, {\"Cat_6_level_1\", type text}, {\"Cat_6_level_2\", type text}, {\"Cat_6_weight\", type text}, {\"Cat_7_level_1\", type text}, {\"Cat_7_level_2\", type text}, {\"Cat_7_weight\", type text}, {\"Cat_8_level_1\", type text}, {\"Cat_8_level_2\", type text}, {\"Cat_8_weight\", type text}, {\"Cat_9_level_1\", type text}, {\"Cat_9_level_2\", type text}, {\"Cat_9_weight\", type text}, {\"Cat_10_level_1\", type text}, {\"Cat_10_level_2\", type text}, {\"Cat_10_weight\", type text}, {\"Cat_11_level_1\", type text}, {\"Cat_11_level_2\", type text}, {\"Cat_11_weight\", type text}, {\"Cat_12_level_1\", type text}, {\"Cat_12_level_2\", type text}, {\"Cat_12_weight\", type text}, {\"labeled\", type logical}})\r\nin\r\n  #\"Changed column type\";\r\nshared enron_05_17_2015_with_labels_v2_100K_chunk_4_of_6 = let\r\n  Source = Csv.Document(Web.Contents(\"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/Documents/Apps/Microsoft Power Query/Uploaded Files/enron_05_17_2015_with_labels_v2_100K_chunk_4_of_6.csv\"), [Delimiter = \",\", Columns = 52, QuoteStyle = QuoteStyle.Csv]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"\", Int64.Type}, {\"Message-ID\", type text}, {\"Date\", type datetime}, {\"From\", type text}, {\"To\", type text}, {\"Subject\", type text}, {\"X-From\", type text}, {\"X-To\", type text}, {\"X-cc\", type text}, {\"X-bcc\", type text}, {\"X-Folder\", type text}, {\"X-Origin\", type text}, {\"X-FileName\", type text}, {\"content\", type text}, {\"user\", type text}, {\"Cat_1_level_1\", type text}, {\"Cat_1_level_2\", type text}, {\"Cat_1_weight\", type text}, {\"Cat_2_level_1\", type text}, {\"Cat_2_level_2\", type text}, {\"Cat_2_weight\", type text}, {\"Cat_3_level_1\", type text}, {\"Cat_3_level_2\", type text}, {\"Cat_3_weight\", type text}, {\"Cat_4_level_1\", type text}, {\"Cat_4_level_2\", type text}, {\"Cat_4_weight\", type text}, {\"Cat_5_level_1\", type text}, {\"Cat_5_level_2\", type text}, {\"Cat_5_weight\", type text}, {\"Cat_6_level_1\", type text}, {\"Cat_6_level_2\", type text}, {\"Cat_6_weight\", type text}, {\"Cat_7_level_1\", type text}, {\"Cat_7_level_2\", type text}, {\"Cat_7_weight\", type text}, {\"Cat_8_level_1\", type text}, {\"Cat_8_level_2\", type text}, {\"Cat_8_weight\", type text}, {\"Cat_9_level_1\", type text}, {\"Cat_9_level_2\", type text}, {\"Cat_9_weight\", type text}, {\"Cat_10_level_1\", type text}, {\"Cat_10_level_2\", type text}, {\"Cat_10_weight\", type text}, {\"Cat_11_level_1\", type text}, {\"Cat_11_level_2\", type text}, {\"Cat_11_weight\", type text}, {\"Cat_12_level_1\", type text}, {\"Cat_12_level_2\", type text}, {\"Cat_12_weight\", type text}, {\"labeled\", type logical}})\r\nin\r\n  #\"Changed column type\";\r\nshared enron_05_17_2015_with_labels_v2_100K_chunk_6_of_6 = let\r\n  Source = Csv.Document(Web.Contents(\"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/Documents/Apps/Microsoft Power Query/Uploaded Files/enron_05_17_2015_with_labels_v2_100K_chunk_6_of_6.csv\"), [Delimiter = \",\", Columns = 52, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"\", type text}, {\"Message-ID\", type text}, {\"Date\", type text}, {\"From\", type text}, {\"To\", type text}, {\"Subject\", type text}, {\"X-From\", type text}, {\"X-To\", type text}, {\"X-cc\", type text}, {\"X-bcc\", type text}, {\"X-Folder\", type text}, {\"X-Origin\", type text}, {\"X-FileName\", type text}, {\"content\", type text}, {\"user\", type text}, {\"Cat_1_level_1\", type text}, {\"Cat_1_level_2\", type text}, {\"Cat_1_weight\", type text}, {\"Cat_2_level_1\", type text}, {\"Cat_2_level_2\", type text}, {\"Cat_2_weight\", type text}, {\"Cat_3_level_1\", type text}, {\"Cat_3_level_2\", type text}, {\"Cat_3_weight\", type text}, {\"Cat_4_level_1\", type text}, {\"Cat_4_level_2\", type text}, {\"Cat_4_weight\", type text}, {\"Cat_5_level_1\", type text}, {\"Cat_5_level_2\", type text}, {\"Cat_5_weight\", type text}, {\"Cat_6_level_1\", type text}, {\"Cat_6_level_2\", type text}, {\"Cat_6_weight\", type text}, {\"Cat_7_level_1\", type text}, {\"Cat_7_level_2\", type text}, {\"Cat_7_weight\", type text}, {\"Cat_8_level_1\", type text}, {\"Cat_8_level_2\", type text}, {\"Cat_8_weight\", type text}, {\"Cat_9_level_1\", type text}, {\"Cat_9_level_2\", type text}, {\"Cat_9_weight\", type text}, {\"Cat_10_level_1\", type text}, {\"Cat_10_level_2\", type text}, {\"Cat_10_weight\", type text}, {\"Cat_11_level_1\", type text}, {\"Cat_11_level_2\", type logical}, {\"Cat_11_weight\", type text}, {\"Cat_12_level_1\", type text}, {\"Cat_12_level_2\", type text}, {\"Cat_12_weight\", type text}, {\"labeled\", type logical}})\r\nin\r\n  #\"Changed column type\";\r\n[Staging = \"DefaultStaging\"]\r\nshared Append = let\r\n  Source = Table.Combine({enron_05_17_2015_with_labels_v2_100K_chunk_1_of_6, enron_05_17_2015_with_labels_v2_100K_chunk_2_of_6, enron_05_17_2015_with_labels_v2_100K_chunk_3_of_6, enron_05_17_2015_with_labels_v2_100K_chunk_4_of_6, enron_05_17_2015_with_labels_v2_100K_chunk_5_of_6, enron_05_17_2015_with_labels_v2_100K_chunk_6_of_6}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"Date\", type text}, {\"Cat_11_level_2\", type text}, {\"labeled\", type text}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"\"})\r\nin\r\n  #\"Removed columns\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared Append_DataDestination = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"8034d15b-bf56-4837-b4d0-97c890988106\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"b02b0681-4b51-445f-bd8c-9993fc7230fc\"]}[Data],\r\n  TableNavigation = Navigation_2{[Item = \"Enron_emails_full_list_v1\", Schema = \"dbo\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[#\"Message-ID\" = nullable text, Date = nullable text, From = nullable text, To = nullable text, Subject = nullable text, #\"X-From\" = nullable text, #\"X-To\" = nullable text, #\"X-cc\" = nullable text, #\"X-bcc\" = nullable text, #\"X-Folder\" = nullable text, #\"X-Origin\" = nullable text, #\"X-FileName\" = nullable text, content = nullable text, user = nullable text, Cat_1_level_1 = nullable text, Cat_1_level_2 = nullable text, Cat_1_weight = nullable text, Cat_2_level_1 = nullable text, Cat_2_level_2 = nullable text, Cat_2_weight = nullable text, Cat_3_level_1 = nullable text, Cat_3_level_2 = nullable text, Cat_3_weight = nullable text, Cat_4_level_1 = nullable text, Cat_4_level_2 = nullable text, Cat_4_weight = nullable text, Cat_5_level_1 = nullable text, Cat_5_level_2 = nullable text, Cat_5_weight = nullable text, Cat_6_level_1 = nullable text, Cat_6_level_2 = nullable text, Cat_6_weight = nullable text, Cat_7_level_1 = nullable text, Cat_7_level_2 = nullable text, Cat_7_weight = nullable text, Cat_8_level_1 = nullable text, Cat_8_level_2 = nullable text, Cat_8_weight = nullable text, Cat_9_level_1 = nullable text, Cat_9_level_2 = nullable text, Cat_9_weight = nullable text, Cat_10_level_1 = nullable text, Cat_10_level_2 = nullable text, Cat_10_weight = nullable text, Cat_11_level_1 = nullable text, Cat_11_level_2 = nullable text, Cat_11_weight = nullable text, Cat_12_level_1 = nullable text, Cat_12_level_2 = nullable text, Cat_12_weight = nullable text, labeled = nullable text], {}), [DeleteWhenEmpty = false])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared Append_WriteToDataDestination = let\r\n  Append_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = Append_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], Append_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  Append_WriteToDataDestination;\r\nshared Append_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(Append, {\"Message-ID\", \"Date\", \"From\", \"To\", \"Subject\", \"X-From\", \"X-To\", \"X-cc\", \"X-bcc\", \"X-Folder\", \"X-Origin\", \"X-FileName\", \"content\", \"user\", \"Cat_1_level_1\", \"Cat_1_level_2\", \"Cat_1_weight\", \"Cat_2_level_1\", \"Cat_2_level_2\", \"Cat_2_weight\", \"Cat_3_level_1\", \"Cat_3_level_2\", \"Cat_3_weight\", \"Cat_4_level_1\", \"Cat_4_level_2\", \"Cat_4_weight\", \"Cat_5_level_1\", \"Cat_5_level_2\", \"Cat_5_weight\", \"Cat_6_level_1\", \"Cat_6_level_2\", \"Cat_6_weight\", \"Cat_7_level_1\", \"Cat_7_level_2\", \"Cat_7_weight\", \"Cat_8_level_1\", \"Cat_8_level_2\", \"Cat_8_weight\", \"Cat_9_level_1\", \"Cat_9_level_2\", \"Cat_9_weight\", \"Cat_10_level_1\", \"Cat_10_level_2\", \"Cat_10_weight\", \"Cat_11_level_1\", \"Cat_11_level_2\", \"Cat_11_weight\", \"Cat_12_level_1\", \"Cat_12_level_2\", \"Cat_12_weight\", \"labeled\"})\r\nin\r\n    SourceTable;\r\n","connectionOverrides":[{"path":"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Web\",\"path\":\"https://endava-my.sharepoint.com/personal/armin_okic_endava_com/\"}","audience":null},{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"Append","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Append.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"Message-ID","dataType":"string"},{"name":"Date","dataType":"string"},{"name":"From","dataType":"string"},{"name":"To","dataType":"string"},{"name":"Subject","dataType":"string"},{"name":"X-From","dataType":"string"},{"name":"X-To","dataType":"string"},{"name":"X-cc","dataType":"string"},{"name":"X-bcc","dataType":"string"},{"name":"X-Folder","dataType":"string"},{"name":"X-Origin","dataType":"string"},{"name":"X-FileName","dataType":"string"},{"name":"content","dataType":"string"},{"name":"user","dataType":"string"},{"name":"Cat_1_level_1","dataType":"string"},{"name":"Cat_1_level_2","dataType":"string"},{"name":"Cat_1_weight","dataType":"string"},{"name":"Cat_2_level_1","dataType":"string"},{"name":"Cat_2_level_2","dataType":"string"},{"name":"Cat_2_weight","dataType":"string"},{"name":"Cat_3_level_1","dataType":"string"},{"name":"Cat_3_level_2","dataType":"string"},{"name":"Cat_3_weight","dataType":"string"},{"name":"Cat_4_level_1","dataType":"string"},{"name":"Cat_4_level_2","dataType":"string"},{"name":"Cat_4_weight","dataType":"string"},{"name":"Cat_5_level_1","dataType":"string"},{"name":"Cat_5_level_2","dataType":"string"},{"name":"Cat_5_weight","dataType":"string"},{"name":"Cat_6_level_1","dataType":"string"},{"name":"Cat_6_level_2","dataType":"string"},{"name":"Cat_6_weight","dataType":"string"},{"name":"Cat_7_level_1","dataType":"string"},{"name":"Cat_7_level_2","dataType":"string"},{"name":"Cat_7_weight","dataType":"string"},{"name":"Cat_8_level_1","dataType":"string"},{"name":"Cat_8_level_2","dataType":"string"},{"name":"Cat_8_weight","dataType":"string"},{"name":"Cat_9_level_1","dataType":"string"},{"name":"Cat_9_level_2","dataType":"string"},{"name":"Cat_9_weight","dataType":"string"},{"name":"Cat_10_level_1","dataType":"string"},{"name":"Cat_10_level_2","dataType":"string"},{"name":"Cat_10_weight","dataType":"string"},{"name":"Cat_11_level_1","dataType":"string"},{"name":"Cat_11_level_2","dataType":"string"},{"name":"Cat_11_weight","dataType":"string"},{"name":"Cat_12_level_1","dataType":"string"},{"name":"Cat_12_level_2","dataType":"string"},{"name":"Cat_12_weight","dataType":"string"},{"name":"labeled","dataType":"string"}]}]}