{"name":"Results from LH to WH","ppdf:dataflowId":"25f45f3e-cbcd-407b-8fc5-9f7a55d33f43","ppdf:owner":{"tenantId":"0b3fc178-b730-4e8b-9843-e81259237b77","userId":"fc487b5c-5b0a-4c85-a873-53170d27b296"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2024-02-23T12:56:44.6888678+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"openai_results":{"queryId":"5ff89d2e-34b5-4320-b078-aecc26be663a","queryName":"openai_results","loadEnabled":true},"openai_results_DataDestination":{"queryId":"7d21f32c-2423-4acb-8b2a-645614db30e0","queryName":"openai_results_DataDestination"},"openai_results_WriteToDataDestination":{"queryId":"7facefbc-12ed-408f-ab26-1c3d600a7e27","queryName":"openai_results_WriteToDataDestination"},"openai_results_TransformForWriteToDataDestination":{"queryId":"f93566a8-afbc-4ce4-a843-32952243cc93","queryName":"openai_results_TransformForWriteToDataDestination"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared openai_results = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"8034d15b-bf56-4837-b4d0-97c890988106\"]}[Data]{[lakehouseId = \"d9def709-2031-4142-83c2-8694c4923a5a\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"openai_results\", ItemKind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared openai_results_DataDestination = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"8034d15b-bf56-4837-b4d0-97c890988106\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"b02b0681-4b51-445f-bd8c-9993fc7230fc\"]}[Data],\r\n  TableNavigation = Navigation_2{[Item = \"openai_results\", Schema = \"dbo\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[ID = nullable text, Category = nullable text, Description = nullable text], {}), [DeleteWhenEmpty = false])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared openai_results_WriteToDataDestination = let\r\n  openai_results_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = openai_results_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], openai_results_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  openai_results_WriteToDataDestination;\r\nshared openai_results_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(openai_results, {\"ID\", \"Category\", \"Description\"})\r\nin\r\n    SourceTable;\r\n","connectionOverrides":[{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null},{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"openai_results","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"openai_results.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"ID","dataType":"string"},{"name":"Category","dataType":"string"},{"name":"Description","dataType":"string"}]}]}